local M = {}

function M.apply()
  local function hi(group)
    vim.api.nvim_set_hl(0, group, { bg = "NONE" })
  end

  hi("Normal")
  hi("NormalNC")
  hi("NormalFloat")
  hi("EndOfBuffer")
  hi("SignColumn")
  hi("FoldColumn")
  hi("Folded")
  hi("CursorLine")
  hi("CursorLineNr")
  hi("LineNr")
  hi("LineNrAbove")
  hi("LineNrBelow")
  hi("Visual")
  hi("VisualNOS")
  hi("Search")
  hi("IncSearch")
  hi("CurSearch")
  hi("MatchParen")
  hi("QuickFixLine")
  hi("Pmenu")
  hi("PmenuSel")
  hi("PmenuSbar")
  hi("PmenuThumb")
  hi("TabLine")
  hi("TabLineSel")
  hi("TabLineFill")
  hi("StatusLine")
  hi("StatusLineNC")
  hi("WinSeparator")
  hi("VertSplit")
  hi("FloatBorder")
  hi("FloatTitle")
  hi("ColorColumn")
  hi("SpecialKey")
  hi("NonText")
  hi("Whitespace")
  hi("Conceal")
  hi("ModeMsg")
  hi("MsgArea")
  hi("MsgSeparator")
  hi("MoreMsg")
  hi("WarningMsg")
  hi("ErrorMsg")
  hi("DiagnosticError")
  hi("DiagnosticWarn")
  hi("DiagnosticInfo")
  hi("DiagnosticHint")
  hi("DiagnosticSignError")
  hi("DiagnosticSignWarn")
  hi("DiagnosticSignInfo")
  hi("DiagnosticSignHint")
  hi("DiagnosticVirtualTextError")
  hi("DiagnosticVirtualTextWarn")
  hi("DiagnosticVirtualTextInfo")
  hi("DiagnosticVirtualTextHint")
  hi("DiagnosticFloatingError")
  hi("DiagnosticFloatingWarn")
  hi("DiagnosticFloatingInfo")
  hi("DiagnosticFloatingHint")
  hi("DiagnosticUnderlineError")
  hi("DiagnosticUnderlineWarn")
  hi("DiagnosticUnderlineInfo")
  hi("DiagnosticUnderlineHint")
  hi("LspReferenceText")
  hi("LspReferenceRead")
  hi("LspReferenceWrite")
  hi("GitSignsAdd")
  hi("GitSignsChange")
  hi("GitSignsDelete")
  hi("TelescopeNormal")
  hi("TelescopeBorder")
  hi("TelescopePromptNormal")
  hi("TelescopePromptBorder")
  hi("TelescopePromptTitle")
  hi("TelescopeResultsNormal")
  hi("TelescopeResultsBorder")
  hi("TelescopeResultsTitle")
  hi("TelescopePreviewNormal")
  hi("TelescopePreviewBorder")
  hi("TelescopePreviewTitle")
  hi("TelescopeSelection")
  hi("TelescopeMatching")
  hi("BufferLineFill")
  hi("BufferLineBackground")
  hi("BufferLineBufferSelected")
  hi("BufferLineBufferVisible")
  hi("BufferLineSeparator")
  hi("BufferLineSeparatorSelected")
  hi("BufferLineSeparatorVisible")
  hi("BufferLineIndicatorSelected")
  hi("NoicePopup")
  hi("NoicePopupBorder")
  hi("NoiceCmdlinePopup")
  hi("NoiceCmdlinePopupBorder")
  hi("NoiceCmdlineIcon")
  hi("NoiceConfirm")
  hi("NoiceConfirmBorder")
  hi("NoiceMini")
  hi("NotifyBackground")
  hi("NotifyERRORBorder")
  hi("NotifyWARNBorder")
  hi("NotifyINFOBorder")
  hi("NotifyDEBUGBorder")
  hi("NotifyTRACEBorder")
  hi("WhichKeyFloat")
  hi("WhichKey")
  hi("WhichKeyGroup")
  hi("WhichKeySeparator")
  hi("WhichKeyDesc")
  hi("WhichKeyBorder")
  hi("TroubleNormal")
  hi("TroubleText")
  hi("TroubleCount")
  hi("TroubleLocation")
  hi("MasonNormal")
  hi("MasonBorder")
  hi("LazyNormal")
  hi("FidgetTitle")
  hi("FidgetTask")
  hi("InclineNormal")
  hi("InclineNormalNC")
  hi("AlphaHeader")
  hi("AlphaButtons")
  hi("AlphaFooter")
  hi("DapBreakpoint")
  hi("DapBreakpointRejected")
  hi("DapStopped")
  hi("DapLogPoint")

  local kinds = {
    "Text", "Method", "Function", "Constructor", "Field", "Variable",
    "Class", "Interface", "Module", "Property", "Unit", "Value", "Enum",
    "Keyword", "Snippet", "Color", "File", "Reference", "Folder",
    "EnumMember", "Constant", "Struct", "Event", "Operator", "TypeParameter",
  }
  for _, kind in ipairs(kinds) do
    hi("BlinkCmpKind" .. kind)
    hi("CmpItemKind" .. kind)
  end
end

return M
