return {
  { import = "plugins.alpha" },
  { import = "plugins.colorscheme" },
  { import = "plugins.cpp" },
  { import = "plugins.fidget" },
  { import = "plugins.integrations" },
  { import = "plugins.kotlin" },
  { import = "plugins.legendary" },
  { import = "plugins.local" },
  { import = "plugins.lsp" },
  { import = "plugins.neoconf" },
  { import = "plugins.obsidian" },
  { import = "plugins.nvim-dap" },
  { import = "plugins.nvim-dapui" },
  { import = "plugins.refactoring" },
  { import = "plugins.telescope" },
  { import = "plugins.testing" },
  { import = "plugins.treesitter" },
  { import = "plugins.trouble" },
  { import = "plugins.typst" },
  { import = "plugins.ui" },
  { import = "plugins.undotree" },
  { import = "plugins.xcode-build" },
}